### ISSUE TITLE
Matters arising from plot_graphs.py

### ISSUE THREAD

**Issue by tomjaguarpaw** [awf/ADBench#109]
Hi @mikhailnikolaev, thanks very much for all your work on the new graph drawing code.  The new graphs look a lot better than the old ones, contain more information, and the code is more coherent too.  There are a few matter that arise from that that we should consider:

1. Your original PR contained a lot of whitespace changes.  Personally, I'm happy with the formatting of the as it currently is.  On the other hand I'm open to discussion and I'm not particularly opposed to whitespace changes.  If we're going to do that we should decide on the format (and perhaps choose an autoformatter) and do the whole file in one whitespace-only commit.  Whitespace changes that occur at the same time as refactorings or functional changes make diffs hard to read.
       a. I am totally fine with wrapping long lines though
2. A lot of the processing occurs at the module top level.  This is pretty bad form.  I think we have two options:
    1. If we're not going to make any more changes to that file then I think it's fine to leave it as it is.  It works.  Let's not try to fix what works.
    2. If we make more changes to this file then first we should pull all executable code into functions and have a `main()` function that is the entry point of the script.  Then new functional changes can be made.

What do you think?

**Comment by mikhailnikolaev** [comment]
Hello, @tomjaguarpaw. I think right now we have others topics to do, so, if current code works, then maybe we can do some refactoring later. (But I think the idea about `main` is absolute right)

**Comment by tomjaguarpaw** [comment]
OK, I'll give awf a chance to look at the outstanding PR and then merge it. Let's come back to these things if we touch the file again in the future.

> By the way, thank you for your help

You're welcome!  I hope it was useful for your understanding.

**Comment by tomjaguarpaw** [comment]
@mikhailnikolaev says:

> I thought when all top-level code was in the same place of the script, code structuring could be simplier. I proposed that such a structuring could be done in the future PR. More over I absolutely don't like when the top level code is not in `if __name__ == "__main__":` block

Yes, I agree with your intentions but I think we need to be careful with `plot_graphs.py` because it is already complicated and fragile.  I suggest that instead of moving everything at the top-level into an `if __name__ == "__main__"` block we move specific segments of the top-level code into functions.  Once we've done that in a way that makes sense then we'll think about how to get rid of the rest of the code from the top-level.

**Comment by tomjaguarpaw** [comment]
I think we have sorted this nicely.  Almost everything lives outside the top level.  There's a tiny bit still left to do but no need to keep this issue open.
