### ISSUE TITLE
Consistent naming

### ISSUE THREAD

**Issue by awf** [awf/ADBench#118]
We should name tools with their tool name and the language/platform, e.g. Julia-Zygote, Python-Autograd.  C++-Finite, C++-Manual, C++-ManualEigen

**Comment by awf** [comment]
At least on the graphs, doesn't need to be root-and-branch.

**Comment by mikhailnikolaev** [comment]
What about this name style: `Tool (language/platform)`? For example `Manual (C++)`

**Comment by awf** [comment]
I was thinking language first, as that will tend to match sorting order.

**Comment by mikhailnikolaev** [comment]
> I was thinking language first, as that will tend to match sorting order.

So, what about `(C++) Manual` ? I propose bracket because, for example, string `C++-Manual` looks rather strange

**Comment by awf** [comment]
I've tried a few, I thinl comma is good:
```
C++, Manual
Julia, Zygote
Python, Autograd
```

**Comment by mikhailnikolaev** [comment]
So, could we close this issue due to PR #133?

**Comment by awf** [comment]
Yes, thanks,
