### ISSUE TITLE
Unable to find type [JacobianComparisonLib.JacobianComparison]

### ISSUE THREAD

**Issue by tomjaguarpaw** [awf/ADBench#120]
I'm trying to run a build on my local machine.  Manual completes fine.  Then after the first run of Finite I see

```
Unable to find type [JacobianComparisonLib.JacobianComparison].
At C:\Users\toelli\source\repos\autodiff\ADBench\run-all.ps1:146 char:12
+     return [JacobianComparisonLib.JacobianComparison]::new($tolerance ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (JacobianComparisonLib.JacobianComparison:TypeName) [], RuntimeExcepti
   on
    + FullyQualifiedErrorId : TypeNotFound
```

(I understand that Finite is the first tool to be checked for correctness because Manual is not checked for correctness.)  Now, in `run-all.ps1` I see the line

```
Add-Type -Path "$bindir/src/dotnet/utils/JacobianComparisonLib/JacobianComparisonLib.dll"
```

`ADBench/cmake-vars.ps1` contains

```
$bindir = "C:/Users/toelli/source/repos/autodiff"
$buildtype = "Release"
$gmm_d_vals = @(2, 10, 20, 32, 64)
$gmm_k_vals = @(5, 10, 25, 50, 100, 200)
```

The `JacobianComparisonLib.dll` file does indeed seem to be where it should be

```
PS C:\Users\toelli\source\repos\autodiff> dir .\src\dotnet\utils\JacobianComparisonLib\JacobianComparisonLib.dll


    Directory: C:\Users\toelli\source\repos\autodiff\src\dotnet\utils\JacobianComparisonLib


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       08/10/2019     14:19           3072 JacobianComparisonLib.dll
```

so at this point I don't see what's wrong?  Why can `run-all.ps1` not access the `JacobianComparisonLib.dll`?  How should I fix this?

**Comment by msdmkats** [comment]
What version of powershell do you use? To get it you can run
```powershell
$PSVersionTable
```

**Comment by tomjaguarpaw** [comment]
Here is the output:

```
PS C:\Users\toelli\source\repos\autodiff> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17763.771
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.771
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by tomjaguarpaw** [comment]
@msdmkats Do I need to update my PowerShell version?

**Comment by msdmkats** [comment]
Well, it won't hurt - my version is
```
Name                           Value
----                           -----
PSVersion                      5.1.18362.145
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.145
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
Our CLR versions are the same, but they cover all versions of framework beginning with 4.6 that does not support `.netstandard2.0`.

`JacobianComparisonLib.dll` is a `netstandard2.0 ` assembly, so it can be loaded from .NET Framework 4.6.1+ and .NET Core 2.0+. That means it should work with both powershell and PS Core.

There's a chance, that your powershell uses .NET Framework 4.6, in which case, update would help, otherwise, I've no idea, what's going on, because the code should work, and on my machine and machines of my colleagues it does.

So, please update your Powershell. If it helps we'll put the version requirement into doc, if not, we'll have to continue investigating.

**Comment by tomjaguarpaw** [comment]
How do I update PowerShell?

**Comment by msdmkats** [comment]
Good question. Windows update, maybe?

Anyway, before you do that, please, try the version in `dmkats/jacobiancomparisonlib` branch. I lowered the .netstandard version there to 1.3.

**Comment by tomjaguarpaw** [comment]
I am not experiencing this problem anymore so I will close this issue.  Thanks for your help!
