### ISSUE TITLE
Why are correctness files assumed to be UTF-16?

### ISSUE THREAD

**Issue by tomjaguarpaw** [awf/ADBench#124]
At the moment the graph plotting code assumes the correctness files are in UTF-16.  Presumably this is correct in Windows, but it is not when I run `run-all.ps1` on Linux.  I have to change to UTF-8.

Is it possible to change the correctness file creation so it is *always* UTF-8, even on Windows?

https://github.com/awf/ADBench/blob/901124fc62ce3b00800296dc353cad40a34052bc/ADBench/plot_graphs.py#L107

**Comment by mikhailnikolaev** [comment]
The problem is that run_all.ps1 produces correctness files in UTF-16. Actually, I don't know how to fix this, but maybe Dmitry does

**Comment by mikhailnikolaev** [comment]
Update. I've found the solution, we can define UTF-8 file encoding in here:
https://github.com/awf/ADBench/blob/901124fc62ce3b00800296dc353cad40a34052bc/ADBench/run-all.ps1#L357

like this:
```PS
$comparison.ToJsonString() | Out-File "${dir_out}${fn}_correctness_${out_name}.txt" -encoding Utf8
```

**Comment by tomjaguarpaw** [comment]
That's great.  @msdmkats would you be happy with this?

**Comment by msdmkats** [comment]
Yes. I've had no idea, the default encoding would be different, I would have specified it otherwise.

**Comment by tomjaguarpaw** [comment]
In fact can we use encoding ASCII?  It would be nice to have an error if we try to output Unicode characters!
