### ISSUE TITLE
BA and Hand plot wrong X axis

### ISSUE THREAD

**Issue by mikhailnikolaev** [awf/ADBench#126]
I've realized what is the problem with graphs for BA and Hand objectives. First of all, X axis has to contain information about input variable count. So, now in the script `ADBench/plot_graphs.py` information about run variable count is extracted from the time file name (respected functions are defined in  `ADBench/utils.py`). File names for GMM and LSTM objectives contain needed information about parameter count (e.g. the typical LSTM time file has the next form `lstm_l2_c1024_times.txt`, so, the script can understand that there was 2 * 1024 variables). But BA and Hand file names have the folowing form:
```
<tool_name><number in order>.txt
```
and for such files the script uses the standard extracting logic, actually, it just concatenates all digits from the file name. Note, that this file name pattern is just taken from data files, stored in the directory `data`.

So, I think that the script `ADBench/run_all.ps1` must generate files for BA and Hand using the same pattern as it is provided for LSTM and GMM. That means that the script has to genrate new file names for result that in general case can be different from data input file names.

Another option is just leaving things as they are. Eventually, we just want to compare tools by their efficiency, I think, we don't need to know how many variables were used.

 What do you think about this?

**Comment by awf** [comment]
Can't we just rename the BA data files?

**Comment by mikhailnikolaev** [comment]
Hmmm... It's strange that I haven't thought about such an obvious solution. Yes, I think it would be the best decision in this situation

**Comment by awf** [comment]
No worries :) Sometimes one is too close to the problem :)

**Comment by mikhailnikolaev** [comment]
Closed due to PR #137
