### ISSUE TITLE
Path to binaries broken

### ISSUE THREAD

**Issue by tomjaguarpaw** [awf/ADBench#19]
@awf, I'm having trouble understanding the intent of this change.  It adds `"\$script:buildtype"` to the path to each tool except DiffSharp.  But the tools don't have that in their path, at least not when I run on Azure DevOps.

The path to the generated Manual binary is `tools\Manual\Tools-Manual-GMM.exe` but, with this change, the script looks for it in `tools\Manual\Release\Tools-Manual-GMM.exe`.

Was it perhaps supposed to be `-neq`, or something else?

https://github.com/awf/autodiff/commit/06ee8d1f911d019098505552887fcc8f48c08ef2#diff-098416d604d473d6991aa60aad51b3bcL165

**Comment by msdmkats** [comment]
Apparently, this change made run_all.ps1 use the paths produced by cmake's `Visual Studio` generator, which differ from those produced by `Ninja` and `Unix Make`. See https://cmake.org/cmake/help/v3.5/prop_tgt/RUNTIME_OUTPUT_DIRECTORY.html#prop_tgt:RUNTIME_OUTPUT_DIRECTORY

**Comment by tomjaguarpaw** [comment]
Closing as fixed by https://github.com/awf/ADBench/pull/39
