### ISSUE TITLE
Rename autodiff->ADbench.

### ISSUE THREAD

**Issue by awf** [awf/ADBench#34]
The repo has been renamed from ``https://github.com/awf/autodiff`` to ``https://github.com/awf/ADBench``.
Check for occurrences and fix.

**Comment by tomjaguarpaw** [comment]
I only found a couple and fixed them: https://github.com/awf/ADBench/commit/c91d0d25e2a81fa8d98c1e26efcb4a5fce6c41aa

**Comment by awf** [comment]
Thanks!
