### ISSUE TITLE
Which tools currently work?

### ISSUE THREAD

**Issue by tomjaguarpaw** [awf/ADBench#70]
I am setting up a CI build for the repository.  At the moment I have enabled `Manual`, `ManualEigen` and `Finite`.   I wonder if you could tell me which tools are currently in a working state and should be tested.

**Comment by awf** [comment]
PyTorch exists on at least one GMM graph, so that's an important test case.

**Comment by msdmkats** [comment]
Autograd, pytorch, julia, and diffsharp seem to work.
I've never tried to actually run Adept, ADOLC, and Ceres.

Though, the updated version of finite is not in master yet, and the one that is doesn't compute the complete jacobian for hand tracking (and saves some time that way). Also, pytorch tool crashes on hand tracking (but works on gmm).

Also, if you're setting a CI build, please, run ctest as a part of it - we have a number of unit tests now.

**Comment by tomjaguarpaw** [comment]
Since the answer to this question will change over time it is best closed!  We will soon provide a CI build that builds and runs all working tools.
