### ISSUE TITLE
Post graphs to gitub pages

### ISSUE THREAD

**Issue by awf** [awf/ADBench#78]
It would be great to have the graphs for the latest build visible somewhere more permanent.  Could we use GitHub pages to semi-automate the process?

**Comment by tomjaguarpaw** [comment]
Fixed by https://github.com/awf/ADBench/commit/53299b88ce6ec77ca110d3fa4aa14d6fd5b31c8d

The graphs are available at https://adbenchwebviewer.azurewebsites.net/
