### ISSUE TITLE
Do DiffSharp problems other than BA work?

### ISSUE THREAD

**Issue by tomjaguarpaw** [awf/ADBench#81]
DiffSharp seems to be configured in `run-all.ps1` to only run for `BA`.  Do the other problems not work?

https://github.com/awf/ADBench/blob/master/ADBench/run-all.ps1#L381

**Comment by novikov-alexander** [comment]
There are a lot of code for GMM and Hand but I didn't check correctness yet.
Moreover, that code doesn't support .NET Core and should be rewritten to some extent.

**Comment by tomjaguarpaw** [comment]
OK, thanks for explaining.
