### ISSUE TITLE
ADOLC is rerun

### ISSUE THREAD

**Issue by tomjaguarpaw** [awf/ADBench#9]
Does anyone have any idea why Tools-ADOLC-Hand-Light-complicated.exe and Tools-ADOLC-Hand-Eigen-complicated.exe keep being rerun?

I see the following even though the ADOLC results have already been generated and ADOLC should be skipped.  It's interesting that number 5 in each case *is* skipped.

```
    complicated_big
      1
Running C:/Users/toelli/CMakeBuilds/b077ec1f-8a7a-9735-b8cb-76f7cb2fcc8e/build/x64-Release\tools\ADOLC\Tools-ADOLC-Hand-Light-complicated.exe
          Hit time limit after 689 loops
          Hit time limit after 18 loops
      2
Running C:/Users/toelli/CMakeBuilds/b077ec1f-8a7a-9735-b8cb-76f7cb2fcc8e/build/x64-Release\tools\ADOLC\Tools-ADOLC-Hand-Light-complicated.exe
          Hit time limit after 682 loops
          Hit time limit after 17 loops
      3
Running C:/Users/toelli/CMakeBuilds/b077ec1f-8a7a-9735-b8cb-76f7cb2fcc8e/build/x64-Release\tools\ADOLC\Tools-ADOLC-Hand-Light-complicated.exe
          Hit time limit after 689 loops
          Hit time limit after 17 loops
      4
Running C:/Users/toelli/CMakeBuilds/b077ec1f-8a7a-9735-b8cb-76f7cb2fcc8e/build/x64-Release\tools\ADOLC\Tools-ADOLC-Hand-Light-complicated.exe
          Hit time limit after 671 loops
          Hit time limit after 17 loops
      5
          Skipped test (already completed)
...
    complicated_big
      1
Running C:/Users/toelli/CMakeBuilds/b077ec1f-8a7a-9735-b8cb-76f7cb2fcc8e/build/x64-Release\tools\ADOLC\Tools-ADOLC-Hand-Eigen-complicated.exe
          Hit time limit after 691 loops
          Hit time limit after 17 loops
      2
Running C:/Users/toelli/CMakeBuilds/b077ec1f-8a7a-9735-b8cb-76f7cb2fcc8e/build/x64-Release\tools\ADOLC\Tools-ADOLC-Hand-Eigen-complicated.exe
          Hit time limit after 700 loops
          Hit time limit after 18 loops
      3
Running C:/Users/toelli/CMakeBuilds/b077ec1f-8a7a-9735-b8cb-76f7cb2fcc8e/build/x64-Release\tools\ADOLC\Tools-ADOLC-Hand-Eigen-complicated.exe
          Hit time limit after 687 loops
          Hit time limit after 17 loops
      4
Running C:/Users/toelli/CMakeBuilds/b077ec1f-8a7a-9735-b8cb-76f7cb2fcc8e/build/x64-Release\tools\ADOLC\Tools-ADOLC-Hand-Eigen-complicated.exe
          Hit time limit after 665 loops
          Hit time limit after 18 loops
      5
          Skipped test (already completed)
```

**Comment by zsmith3** [comment]
I haven't got it set up on my computer, but I think:
- in `ADOLC/main.cpp` (line 673), the name is set in full caps `"ADOLC_eigen"`
- in `ADBench/run-all.ps1` (line 152), the name for eigen tests is lower-case (`"adolc_eigen"`)
    - I set it this way because that's how `Manual/main.cpp` was naming it
    - It should probably be changed across all of the different tools to just maintain the name of the tool (i.e. `$this.name` instead of `$this.name.ToLower()`). However this will require changes to other tools - the fastest solution would be to make it lower case in `ADOLC/main.cpp` (line 673).
- I think this causes the issue with `run-all.ps1` not recognising that the first 4 tests have already been completed
- A possible explanation for skipping number 5 is that, on some previous run, the program exceeded the maximum time limit set in `run-all.ps1`, so it was terminated early. When `run-all.ps1` terminates a program early, it saves a results file with `"inf inf"` as the times (see line 57), to mark that the test was attempted but timed out. Since this file is generated by `run-all.ps1`, it would follow the lower-case naming and so is detected.

**Comment by zsmith3** [comment]
For me, no output .txt files actually show up under `/tmp/Debug/hand/complicated_small/ADOLC/`. I added `std:cout` statements throughout the ADOL-C code, and found that it crashed somewhere during the `compute_hand_J` function (see line 559 of `ADOLC/main.cpp`), but the exact point where it crashes seems to vary slightly (sometimes it got up to line 635, sometimes crashed before line 601).

Is the problem the same for you? If so then it seems to be a more complicated issue with ADOL-C, and I'm not sure how to solve it.

**Comment by zsmith3** [comment]
Ah, ok. Could try adding something like:
`Write-Host $output_file`
after line 156 of `run-all.ps1`, and compare that path with the path to the output files you can see.
Maybe also add:
`Write-Host $script:repeat`
just to check this is false.

**Comment by tomjaguarpaw** [comment]
I will give it a go. Thanks for your help @zsmith3!

**Comment by tomjaguarpaw** [comment]
Interesting.  `compute_hand_J` seems to crash for me in `Release` mode, but not `Debug`.  I'm investigating further ...

**Comment by tomjaguarpaw** [comment]
I can't see anything obviously wrong with it but I guess it must be segfaulting.  I'll disable ADOL-C for now.  Thanks @zsmith3!

**Comment by tomjaguarpaw** [comment]
Closing as stale.
